project:
  type: book

book:
  title: "Evangel Presbytery Bylaws"
  author: "Evangel Presbytery"
  description: "*This is the official Bylaws for Evangel Presbytery. You can always find the latest online version at https://bylaws.evangelpresbytery.com. A record of the changes can be found in the [Updates](01-updates.qmd) section at the end of the book.*"
  date: today
  repo-url: https://github.com/Evangel-Presbytery/evangel-bylaws
  chapters:
    - index.qmd
    - 00-bylaws.qmd
    - 01-updates.qmd
  sidebar:
    header: TOCheader.qmd
    search: true
  favicon: "logo.png"

format:
  html:
    number-sections: false
    css: "style.css"
    footnotes-hover: false
    include-in-header:
      - text: <script src="https://kit.fontawesome.com/c2565ebea9.js" crossorigin="anonymous"></script>
