project:
  type: book
  post-render:
    - scripts/fix_links.py
    - scripts/fix_search_highlight.py

date: today
date-format: "MMMM D, YYYY"

book:
  title: "Evangel Presbytery Bylaws"
  description: "<br>These are the official Bylaws for [Evangel Presbytery](https://evangelpresbytery.com). You can always find the latest online version at <https://bylaws.evangelpresbytery.com>. A record of the changes can be found in the [Updates](01-updates.qmd) section at the end of the book. <p>Last updated on {{< meta date >}}.</p>"
  repo-url: https://github.com/Evangel-Presbytery/evangel-bylaws
  chapters:
    - index.qmd
    - 01-updates.qmd
  sidebar:
    header: TOCheader.qmd
    search: true
  favicon: "evangel-favicon-196.png"
  navbar: 
    title: false
    logo: logo-white.png
    logo-href: https://evangelpresbytery.com
    search: false
    left:
      - text: Book of Church Order
        href: https://bco.evangelpresbytery.com
      - text: Doctrinal Declarations
        href: https://ddp.evangelpresbytery.com
      - text: Bylaws
        href: https://bylaws.evangelpresbytery.com

format:
  html:
    number-sections: false
    css: "style.css"
    toc-location: left
    footnotes-hover: false
    include-in-header: in_header.html
